import type { Project, Sector, Delivery } from '@/types';

export const sectorLabel: Record<Sector, string> = {
  healthcare: 'Healthcare',
  laboratory: 'Laboratory',
  'higher-ed': 'Higher education',
  k12: 'K-12',
  office: 'Office',
  'data-center': 'Data center',
  industrial: 'Industrial',
  civic: 'Civic',
};

export const deliveryLabel: Record<Delivery, string> = {
  'new-construction': 'New construction',
  'retro-commissioning': 'Retro-commissioning',
  recertification: 'Recertification',
  'tenant-fitout': 'Tenant fit-out',
};

export const projects: Project[] = [
  {
    slug: 'st-vrain-regional-medical',
    title: 'St. Vrain Regional Medical Center, Patient Tower',
    client: 'St. Vrain Health Partners',
    location: 'Longmont, CO',
    sector: 'healthcare',
    delivery: 'new-construction',
    services: ['air-balancing', 'hydronic-balancing', 'commissioning'],
    year: '2024',
    squareFeet: 214_000,
    featured: true,
    brief: [
      'A six-story patient tower with 96 beds, four operating rooms, and a sterile processing suite, delivered under a GMP with a hospital opening date that had already been announced to the public.',
      'DATUM held the commissioning and TAB contract directly with the health system, not with the construction manager. That structure was the owner’s decision after a previous project where the balance report and the field conditions did not agree.',
    ],
    approach: [
      'Two design reviews, at design development and 90% CDs, produced 78 comments. Nineteen changed a drawing. The most consequential was an OR pressure cascade that could not have been achieved with the return air path as drawn.',
      'All 611 terminals were measured. Operating room and sterile processing air change rates and pressure relationships were tested with doors closed, in the operating mode required by FGI, with the anesthesia booms in place.',
      'Functional testing exercised every unique sequence including emergency power transfer with mechanical load connected. That is the test most often deferred, and most often failed.',
    ],
    outcome: [
      '104 deficiencies logged, all closed before licensure inspection. Four required a design change, 31 required contractor rework, the rest were controls.',
      'The OR suite passed state licensure on the first inspection with pressure and air change documentation taken directly from our report.',
      'Emergency power transfer failed on first test: two air handlers were on the wrong branch and would have dropped during a transfer. Corrected and re-tested before occupancy.',
    ],
    metrics: [
      { value: 611, label: 'Terminals measured' },
      { value: 104, label: 'Deficiencies logged' },
      { value: 100, suffix: '%', label: 'Closed before licensure' },
      { value: 78, label: 'Design review comments' },
    ],
    comparison: [
      { tag: 'OR-3', label: 'Operating room 3, supply', design: 2400, measured: 2388, unit: 'cfm', tolerance: 5 },
      { tag: 'OR-3', label: 'Operating room 3, pressure', design: 0.03, measured: 0.031, unit: 'in wg', tolerance: 15 },
      { tag: 'AHU-4', label: 'Tower AHU, outside air', design: 9600, measured: 9540, unit: 'cfm', tolerance: 5 },
      { tag: 'SPD-1', label: 'Sterile processing, decontam', design: 1800, measured: 1104, unit: 'cfm', tolerance: 5 },
      { tag: 'CHW-P2', label: 'Chilled water, secondary', design: 1250, measured: 1238, unit: 'gpm', tolerance: 5 },
      { tag: 'EF-7', label: 'Soiled utility exhaust', design: 900, measured: 872, unit: 'cfm', tolerance: 10 },
    ],
    deficiencies: [
      {
        id: 'DEF-041',
        system: 'SPD-1',
        location: 'L2 · Sterile processing, decontamination',
        severity: 'critical',
        state: 'verified',
        finding:
          'Supply 39% below design. Decontamination room could not hold negative pressure to the clean side with the pass-through door closed.',
        action:
          'Fire-smoke damper FSD-2-14 found at 55% open, actuator linkage installed against the stop. Contractor to correct and DATUM to re-test.',
        opened: '2024-03-11',
        closed: '2024-03-26',
      },
      {
        id: 'DEF-052',
        system: 'ATS-2 / AHU-4, AHU-5',
        location: 'Penthouse',
        severity: 'critical',
        state: 'verified',
        finding:
          'On simulated utility loss, AHU-4 and AHU-5 did not restart. Both fed from a non-essential distribution branch, contrary to sheet E-501.',
        action: 'Electrical contractor to re-feed from essential branch. Full transfer test repeated with mechanical load.',
        opened: '2024-04-02',
        closed: '2024-04-30',
      },
      {
        id: 'DEF-067',
        system: 'VAV-3-22 through VAV-3-29',
        location: 'L3 · Med-surg east',
        severity: 'major',
        state: 'verified',
        finding: 'Eight boxes with minimum airflow set below the manufacturer’s measurable range; controller reporting flow that the box cannot resolve.',
        action: 'Controls contractor to reset minimums per schedule; DATUM to re-measure at minimum and maximum.',
        opened: '2024-04-15',
        closed: '2024-05-09',
      },
      {
        id: 'DEF-088',
        system: 'AHU-2',
        location: 'Penthouse',
        severity: 'minor',
        state: 'verified',
        finding: 'Static pressure reset sequence programmed but disabled at the controller. Fan holding 1.5 in wg at all loads.',
        action: 'Enable reset and trend for two weeks.',
        opened: '2024-05-06',
        closed: '2024-05-22',
      },
    ],
    spec: [
      'Commissioning: ASHRAE Guideline 0-2019, Standard 202-2018',
      'TAB: NEBB Procedural Standard, 8th edition',
      'Healthcare ventilation: ASHRAE 170-2021, FGI Guidelines 2022',
      'Contract held directly with owner',
    ],
    testimonial: {
      quote:
        'We had a balance report on the last building that said everything was within tolerance. It was not. This time the report told us about a decontamination room at 61% of design three weeks before we would have found it during a licensure survey. That is what we were paying for.',
      name: 'Gwen Marchetti',
      role: 'Vice President, Facilities',
      company: 'St. Vrain Health Partners',
    },
    seed: 3,
    seo: {
      title: 'St. Vrain Regional Medical Center | Healthcare Commissioning | DATUM',
      description:
        'Commissioning and TAB for a 214,000 sq ft patient tower: 611 terminals measured, 104 deficiencies logged and closed before state licensure inspection.',
    },
  },
  {
    slug: 'mesa-verde-life-sciences',
    title: 'Mesa Verde Life Sciences Building',
    client: 'Front Range State University',
    location: 'Boulder, CO',
    sector: 'laboratory',
    delivery: 'new-construction',
    services: ['air-balancing', 'fume-hood-testing', 'commissioning'],
    year: '2023',
    squareFeet: 96_000,
    featured: true,
    brief: [
      'Forty-two variable air volume fume hoods across three research floors, with a manifolded exhaust system and heat recovery, on a campus whose EHS office had been burned once already by hoods that passed face velocity and failed containment.',
      'The university wrote ASHRAE 110 as-installed testing into the specification and required an independent agency, structurally separate from the mechanical contractor.',
    ],
    approach: [
      'Every hood tested to ASHRAE 110 as-installed at the sash height in the researcher’s standard operating procedure, not only at the 18-inch design height.',
      'Room-level cross-draft mapping at each hood face before containment testing, so a failure could be attributed to the hood or to the room.',
      'Manifolded exhaust system tested at minimum and maximum diversity, including the bypass condition when all hoods close simultaneously.',
    ],
    outcome: [
      'Nine hoods failed as-installed containment. Seven were room problems: supply diffusers throwing directly across the hood face.',
      'Diffuser relocation and throw pattern changes brought all nine into compliance without touching a hood.',
      'System diversity testing found the manifold could not maintain minimum stack velocity with 38 of 42 sashes closed. Bypass sequence rewritten before occupancy.',
    ],
    metrics: [
      { value: 42, label: 'Fume hoods tested' },
      { value: 9, label: 'As-installed failures' },
      { value: 7, label: 'Caused by the room, not the hood' },
      { value: 0.05, decimals: 2, suffix: ' ppm', label: 'Control level achieved' },
    ],
    comparison: [
      { tag: 'FH-2-07', label: 'Hood face velocity, 18 in', design: 100, measured: 98, unit: 'fpm', tolerance: 10 },
      { tag: 'FH-2-07', label: 'Hood face velocity, 28 in', design: 100, measured: 71, unit: 'fpm', tolerance: 10 },
      { tag: 'FH-3-11', label: 'Cross-draft at face', design: 30, measured: 88, unit: 'fpm', tolerance: 20 },
      { tag: 'EF-MAN', label: 'Stack velocity, min diversity', design: 3000, measured: 2180, unit: 'fpm', tolerance: 10 },
      { tag: 'AHU-L3', label: 'Lab supply, total', design: 32000, measured: 31760, unit: 'cfm', tolerance: 5 },
    ],
    deficiencies: [
      {
        id: 'DEF-014',
        system: 'FH-3-09 through FH-3-15',
        location: 'L3 · Research lab 340',
        severity: 'critical',
        state: 'verified',
        finding:
          'Seven hoods failed ASHRAE 110 AI at 0.05 ppm control level. Cross-draft at the hood face measured 78 to 94 fpm against a 30 fpm criterion.',
        action:
          'Relocate three supply diffusers and change throw pattern on four. Re-test all seven hoods after modification.',
        opened: '2023-08-14',
        closed: '2023-09-28',
      },
      {
        id: 'DEF-022',
        system: 'EF-MAN, manifolded exhaust',
        location: 'Roof',
        severity: 'critical',
        state: 'verified',
        finding:
          'At 38 of 42 sashes closed, stack discharge velocity fell to 2,180 fpm against a 3,000 fpm minimum required for plume rise.',
        action: 'Rewrite bypass damper sequence to hold minimum stack velocity at all diversity conditions. Re-test.',
        opened: '2023-08-22',
        closed: '2023-10-11',
      },
      {
        id: 'DEF-031',
        system: 'FH-2-07',
        location: 'L2 · Research lab 218',
        severity: 'major',
        state: 'verified',
        finding: 'Sash alarm set point at 74 fpm, below the velocity required to maintain containment at the working sash height.',
        action: 'Reset alarm to 80 fpm and verify audible and visual annunciation.',
        opened: '2023-09-05',
        closed: '2023-09-19',
      },
    ],
    spec: [
      'Fume hood containment: ASHRAE 110-2016, as-installed',
      'Laboratory ventilation: ANSI/AIHA Z9.5, NFPA 45',
      'TAB: NEBB Procedural Standard, 8th edition',
      'Independent agency required by specification',
    ],
    testimonial: {
      quote:
        'The finding that mattered was not about a hood at all. It was that our own supply diffusers were blowing contaminant back into the researcher’s face. No one had ever measured the room.',
      name: 'Dr. Nadia Bergström',
      role: 'Director, Environmental Health & Safety',
      company: 'Front Range State University',
    },
    seed: 8,
    seo: {
      title: 'Mesa Verde Life Sciences Building | Fume Hood Containment | DATUM',
      description:
        'ASHRAE 110 as-installed testing of 42 VAV fume hoods. Nine containment failures identified, seven traced to room air distribution rather than the hoods.',
    },
  },
  {
    slug: 'arapahoe-justice-center',
    title: 'Arapahoe County Justice Center',
    client: 'Arapahoe County Facilities',
    location: 'Centennial, CO',
    sector: 'civic',
    delivery: 'retro-commissioning',
    services: ['retro-commissioning', 'air-balancing'],
    year: '2024',
    squareFeet: 340_000,
    featured: true,
    brief: [
      'A 1998 courthouse and detention facility with energy use 41% above the median for its type, a capital request on the table for two new chillers, and no evidence that the existing chillers were the problem.',
      'The county engaged DATUM to determine whether the building had an equipment problem or an operations problem before releasing the capital.',
    ],
    approach: [
      'Four weeks of BAS trends at fifteen-minute intervals, pulled before anyone walked the building. Simultaneous heating and cooling appeared in 31 of 88 zones.',
      'Portable power metering on both chillers, all pumps, and four air handlers to reconcile the trends against actual demand.',
      'Every finding costed against the county’s actual utility tariff, with implementation priced from three subcontractor quotes.',
    ],
    outcome: [
      'The chillers were fine. Chilled water supply temperature had been overridden to 42°F at the operator workstation in 2019 and never returned to the reset schedule.',
      '$214,000 in annual savings identified across 19 measures. $61,000 required no capital at all: schedules, setpoints, and removing overrides.',
      'The chiller replacement was deferred. Twelve-month M&V confirmed $198,400 realized against $214,000 predicted, a 93% capture rate.',
    ],
    metrics: [
      { value: 214, prefix: '$', suffix: 'K', label: 'Annual savings identified' },
      { value: 198.4, prefix: '$', suffix: 'K', decimals: 1, label: 'Verified at 12 months' },
      { value: 19, label: 'Measures implemented' },
      { value: 0.9, decimals: 1, suffix: ' yr', label: 'Blended simple payback' },
    ],
    comparison: [
      { tag: 'CH-1', label: 'Chilled water supply temp', design: 44, measured: 42, unit: '°F', tolerance: 4 },
      { tag: 'SYS', label: 'Chilled water delta-T', design: 12, measured: 6.4, unit: '°F', tolerance: 10 },
      { tag: 'AHU-6', label: 'Duct static setpoint', design: 1.0, measured: 1.75, unit: 'in wg', tolerance: 10 },
      { tag: 'SYS', label: 'Zones in simultaneous H&C', design: 0, measured: 31, unit: 'zones', tolerance: 0 },
      { tag: 'OA-2', label: 'Outside air, minimum position', design: 15, measured: 42, unit: '%', tolerance: 10 },
    ],
    deficiencies: [
      {
        id: 'RCX-003',
        system: 'CH-1 / CH-2',
        location: 'Central plant',
        severity: 'critical',
        state: 'verified',
        finding:
          'Chilled water supply temperature held at 42°F year-round. Reset schedule present in the BAS but overridden at the operator workstation since 09/2019.',
        action: 'Remove override, re-enable reset schedule, trend for 30 days. Estimated saving $31,200/yr.',
        opened: '2024-01-18',
        closed: '2024-02-06',
      },
      {
        id: 'RCX-007',
        system: '31 VAV zones',
        location: 'Floors 2 to 4, east and south',
        severity: 'major',
        state: 'verified',
        finding:
          'Simultaneous heating and cooling in 31 zones. Box minimums set at 40% of maximum against a 20% design, forcing reheat to satisfy the space.',
        action: 'Reset minimums per original schedule and re-balance affected boxes. Estimated saving $54,800/yr.',
        opened: '2024-01-24',
        closed: '2024-03-15',
      },
      {
        id: 'RCX-011',
        system: 'AHU-3, AHU-6',
        location: 'Mechanical 4A',
        severity: 'major',
        state: 'verified',
        finding: 'Static pressure setpoint raised to 1.75 in wg in response to a 2017 complaint; reset never re-enabled.',
        action: 'Restore reset with 0.6 in wg minimum. Estimated saving $22,400/yr.',
        opened: '2024-01-24',
        closed: '2024-02-20',
      },
      {
        id: 'RCX-016',
        system: 'AHU-1 through AHU-8',
        location: 'Building-wide',
        severity: 'minor',
        state: 'verified',
        finding: 'Outside air minimum damper position 42% against a calculated ventilation requirement of 15%.',
        action: 'Rebalance minimum OA to code requirement with CO2 reset above. Estimated saving $18,900/yr.',
        opened: '2024-02-02',
        closed: '2024-03-28',
      },
    ],
    spec: [
      'Retro-commissioning: ASHRAE Guideline 0.2-2015',
      'M&V: IPMVP Option C, whole-building, 12-month',
      'Trend interval: 15 minutes, 4-week baseline',
      'Utility incentive: Xcel Energy RCx program',
    ],
    testimonial: {
      quote:
        'We were eleven days from releasing $1.4 million for chillers that turned out to be working correctly. The study cost $48,000.',
      name: 'Curtis Nakamura',
      role: 'Facilities Director',
      company: 'Arapahoe County',
    },
    seed: 5,
    seo: {
      title: 'Arapahoe County Justice Center | Retro-Commissioning | DATUM',
      description:
        'Retro-commissioning of a 340,000 sq ft courthouse: $214K annual savings identified, $198.4K verified at 12 months, a $1.4M chiller replacement deferred.',
    },
  },
  {
    slug: 'halverson-pharmaceuticals',
    title: 'Halverson Pharmaceuticals, Sterile Suite B',
    client: 'Halverson Pharmaceuticals',
    location: 'Golden, CO',
    sector: 'industrial',
    delivery: 'recertification',
    services: ['cleanroom-certification', 'air-balancing'],
    year: '2025',
    squareFeet: 28_000,
    featured: false,
    brief: [
      'An ISO Class 7 sterile compounding suite with an ISO Class 5 primary engineering control, due for annual recertification with an FDA pre-approval inspection scheduled eleven weeks out.',
      'The previous year’s certificate did not state the occupancy state it was tested in, which is the kind of omission that turns a routine inspection into a finding.',
    ],
    approach: [
      'Full ISO 14644-1:2015 classification in both at-rest and operational states, with the operational test run during an actual compounding shift.',
      'Installed filter leakage scanning on all 34 HEPA filters and their seals, with leaks located and marked rather than reported as a pass or fail count.',
      'Recovery testing and airflow visualization recorded on video for the quality file.',
    ],
    outcome: [
      'Two filter seal leaks found at 0.019% and 0.024% against a 0.01% criterion. Both at the same corner detail, indicating an installation pattern rather than a filter defect.',
      'Anteroom to buffer room pressure cascade found reversed with the door closed: the buffer room was the lower pressure of the two.',
      'Suite recertified in both occupancy states, with the state named on the certificate. Inspection closed with no observations on the environmental control system.',
    ],
    metrics: [
      { value: 34, label: 'HEPA filters scanned' },
      { value: 2, label: 'Seal leaks located' },
      { value: 7, label: 'ISO class certified' },
      { value: 0, label: 'Inspection observations' },
    ],
    comparison: [
      { tag: 'BUF-1', label: 'Buffer room, air changes', design: 30, measured: 31.4, unit: 'ACH', tolerance: 10 },
      { tag: 'BUF-1', label: 'Buffer to anteroom, ΔP', design: 0.02, measured: -0.004, unit: 'in wg', tolerance: 25 },
      { tag: 'PEC-2', label: 'ISO 5 hood, face velocity', design: 90, measured: 92, unit: 'fpm', tolerance: 10 },
      { tag: 'ANT-1', label: 'Anteroom, air changes', design: 20, measured: 19.2, unit: 'ACH', tolerance: 10 },
      { tag: 'BUF-1', label: 'Recovery time', design: 20, measured: 11, unit: 'min', tolerance: 20 },
    ],
    deficiencies: [
      {
        id: 'CR-002',
        system: 'BUF-1 / ANT-1',
        location: 'Sterile suite B',
        severity: 'critical',
        state: 'verified',
        finding:
          'Pressure cascade reversed with the pass-through door closed. Buffer room measured 0.004 in wg negative to the anteroom against a required 0.02 in wg positive.',
        action: 'Rebalance return and general exhaust; verify with door in both positions. Re-test cascade.',
        opened: '2025-02-04',
        closed: '2025-02-19',
      },
      {
        id: 'CR-005',
        system: 'HEPA F-14, F-22',
        location: 'Buffer room ceiling grid',
        severity: 'major',
        state: 'verified',
        finding: 'Installed filter leakage 0.019% and 0.024% at the downstream corner seal, against a 0.01% acceptance criterion.',
        action: 'Reseat and re-gasket both filters; re-scan full seal perimeter.',
        opened: '2025-02-04',
        closed: '2025-02-12',
      },
    ],
    spec: [
      'Classification: ISO 14644-1:2015',
      'Test methods: ISO 14644-3:2019',
      'Compounding: USP <797>, USP <800>',
      'Particle counter: ISO 21501-4 compliant',
    ],
    seed: 12,
    seo: {
      title: 'Halverson Pharmaceuticals Sterile Suite | ISO 14644 | DATUM',
      description:
        'Annual ISO 14644-1 recertification of an ISO Class 7 sterile compounding suite: 34 filters scanned, two seal leaks located, reversed pressure cascade corrected.',
    },
  },
  {
    slug: 'cheyenne-ridge-middle-school',
    title: 'Cheyenne Ridge Middle School',
    client: 'Poudre Valley School District R-2',
    location: 'Fort Collins, CO',
    sector: 'k12',
    delivery: 'new-construction',
    services: ['air-balancing', 'sound-vibration', 'commissioning'],
    year: '2023',
    squareFeet: 128_000,
    featured: false,
    brief: [
      'A new middle school with displacement ventilation in classrooms and an acoustic specification of NC-30, driven by ANSI S12.60 classroom acoustics requirements the district had adopted district-wide.',
      'The district had two previous schools where classrooms measured above NC-40 and teachers had been complaining since opening.',
    ],
    approach: [
      'Octave band sound measurement in 22 sample classrooms, with background levels taken with all mechanical systems off at 5:30am.',
      'Source attribution by shutting down each system individually while measurement continued, which turned a composite level into an attributable one.',
      'Displacement diffuser flows verified at low face velocity, where standard capture hood technique introduces significant error and requires back-pressure compensation.',
    ],
    outcome: [
      'Fourteen classrooms measured NC-36 to NC-41 against an NC-30 specification, all on the same two air handlers.',
      'The governing band was 125 Hz across all fourteen rooms: fan blade pass frequency, transmitted through a return path with no lining in the first 18 feet.',
      'Lining added to the return plenum and a fan speed change moved blade pass off the room mode. All fourteen rooms re-measured at NC-29 or better.',
    ],
    metrics: [
      { value: 22, label: 'Classrooms measured' },
      { value: 14, label: 'Over the NC-30 criterion' },
      { value: 125, suffix: ' Hz', label: 'Governing octave band' },
      { value: 29, label: 'Final NC, worst room' },
    ],
    comparison: [
      { tag: 'RM-214', label: 'Classroom 214, NC level', design: 30, measured: 41, unit: 'NC', tolerance: 5 },
      { tag: 'RM-214', label: 'Classroom 214, after correction', design: 30, measured: 28, unit: 'NC', tolerance: 5 },
      { tag: 'AHU-2', label: 'Supply fan, total', design: 18500, measured: 18320, unit: 'cfm', tolerance: 5 },
      { tag: 'DV-214', label: 'Displacement diffuser', design: 340, measured: 331, unit: 'cfm', tolerance: 10 },
    ],
    deficiencies: [
      {
        id: 'SV-001',
        system: 'AHU-2, AHU-3',
        location: '14 classrooms, wings B and C',
        severity: 'major',
        state: 'verified',
        finding:
          'NC-36 to NC-41 against an NC-30 specification. Governing band 125 Hz, coincident with fan blade pass frequency at design speed.',
        action:
          'Line first 18 ft of return plenum and adjust fan speed to move blade pass off the coincident mode. Re-measure all 14 rooms.',
        opened: '2023-06-12',
        closed: '2023-07-27',
      },
      {
        id: 'SV-004',
        system: 'RTU-1',
        location: 'Roof over administration',
        severity: 'minor',
        state: 'verified',
        finding: 'Spring isolators fully compressed. Unit as delivered was 380 lb heavier than the submittal used for isolator selection.',
        action: 'Replace isolators with correctly sized springs; verify 1 in operating deflection.',
        opened: '2023-06-12',
        closed: '2023-08-04',
      },
    ],
    spec: [
      'Classroom acoustics: ANSI/ASA S12.60-2010',
      'Sound measurement: Type 1 meter, octave bands 63 Hz to 8 kHz',
      'TAB: NEBB Procedural Standard, 8th edition',
      'Commissioning: ASHRAE Guideline 0-2019',
    ],
    seed: 21,
    seo: {
      title: 'Cheyenne Ridge Middle School | Classroom Acoustics & TAB | DATUM',
      description:
        'Sound testing and balancing for a 128,000 sq ft school: 14 classrooms over the NC-30 criterion traced to fan blade pass at 125 Hz and corrected.',
    },
  },
  {
    slug: 'front-range-data-hall',
    title: 'Front Range Data Hall 3',
    client: 'Meridian Digital Infrastructure',
    location: 'Aurora, CO',
    sector: 'data-center',
    delivery: 'retro-commissioning',
    services: ['retro-commissioning', 'air-balancing', 'hydronic-balancing'],
    year: '2025',
    squareFeet: 62_000,
    featured: false,
    brief: [
      'A colocation hall at 68% of design IT load running a PUE of 1.61 against a 1.35 design, with three of twelve CRAH units in mechanical cooling while return air temperature suggested none should be.',
      'Testing had to be done live. There was no maintenance window that involved taking a hall offline.',
    ],
    approach: [
      'Full airflow and pressure mapping of the raised floor and containment aisles under live load, using tracer methods that do not require shutting anything down.',
      'Chilled water flow verified ultrasonically at each CRAH, because the balancing valves had no functioning pressure ports.',
      'Trend reconciliation across the CRAH fleet to find units fighting each other on humidity control.',
    ],
    outcome: [
      'Four CRAH units were dehumidifying while three others humidified, a $46,000/yr circular process caused by three humidity sensors reading 9 to 14% RH high.',
      'Bypass airflow through unsealed floor cutouts measured at 22% of total supply. Sealing was a two-day, $9,000 scope.',
      'PUE improved from 1.61 to 1.39 with no equipment replaced. Verified over six months of metered data.',
    ],
    metrics: [
      { value: 1.61, decimals: 2, label: 'PUE before' },
      { value: 1.39, decimals: 2, label: 'PUE after' },
      { value: 22, suffix: '%', label: 'Bypass airflow found' },
      { value: 46, prefix: '$', suffix: 'K', label: 'Humidity fight, annual' },
    ],
    comparison: [
      { tag: 'HALL-3', label: 'Bypass airflow, % of supply', design: 5, measured: 22, unit: '%', tolerance: 20 },
      { tag: 'CRAH-04', label: 'Return air temperature', design: 95, measured: 78, unit: '°F', tolerance: 5 },
      { tag: 'CRAH-07', label: 'Space RH, sensor reading', design: 45, measured: 57, unit: '%', tolerance: 10 },
      { tag: 'CHW', label: 'Chilled water delta-T', design: 14, measured: 7.2, unit: '°F', tolerance: 10 },
      { tag: 'HALL-3', label: 'Cold aisle static, containment', design: 0.02, measured: 0.004, unit: 'in wg', tolerance: 25 },
    ],
    deficiencies: [
      {
        id: 'DC-002',
        system: 'CRAH-02, 05, 07, 11',
        location: 'Data hall 3',
        severity: 'critical',
        state: 'verified',
        finding:
          'Four units in dehumidification while three humidified simultaneously. Three space humidity sensors reading 9 to 14% RH above calibrated reference.',
        action: 'Recalibrate or replace sensors; move humidity control to a single hall-level averaged sensor. Estimated saving $46,000/yr.',
        opened: '2025-04-08',
        closed: '2025-05-02',
      },
      {
        id: 'DC-006',
        system: 'Raised floor, hall 3',
        location: 'Rows 4 to 11',
        severity: 'major',
        state: 'verified',
        finding: 'Bypass airflow 22% of total supply through unsealed cable cutouts and two missing floor tiles under row 9.',
        action: 'Install brush grommets at all cutouts; replace missing tiles. Re-map cold aisle static after sealing.',
        opened: '2025-04-08',
        closed: '2025-04-24',
      },
      {
        id: 'DC-009',
        system: 'CRAH fleet, chilled water',
        location: 'Data hall 3',
        severity: 'major',
        state: 'verified',
        finding: 'System delta-T 7.2°F against 14°F design. Nine of twelve control valves passing at 100% open with no modulation observed in trends.',
        action: 'Replace oversized two-way valves on nine units; proportionally re-balance the loop.',
        opened: '2025-04-15',
        closed: '2025-06-11',
      },
    ],
    spec: [
      'Retro-commissioning: ASHRAE Guideline 0.2-2015',
      'Thermal guidelines: ASHRAE TC 9.9, 2021',
      'Live-load testing, no scheduled downtime',
      'M&V: IPMVP Option B, 6-month',
    ],
    seed: 17,
    seo: {
      title: 'Front Range Data Hall 3 | Data Center Retro-Commissioning | DATUM',
      description:
        'Live-load retro-commissioning of a 62,000 sq ft colocation hall: PUE from 1.61 to 1.39 with no equipment replaced, 22% bypass airflow eliminated.',
    },
  },
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export const featuredProjects = projects.filter((p) => p.featured);
